---
services:
  back-end:
    build: 
      context: Backend
      dockerfile: Dockerfile
    ports:
      - 8090:8080
    environment:
      DB_URL: jdbc:mysql://34.133.94.207/eventsblitz
      DB_USERNAME: root
      DB_PASSWORD: seng401

  front-end:
    build:
      context: Frontend/eventsblitzfrontend
      dockerfile: Dockerfile
    ports:
      - 80:3000
    depends_on:
      - back-end
